[feature] Add Poetry as dependency management system and packaging
omadson/fuzzy-c-means pull request #6
Opened 2020-10-22 00:53 UTC by zealberth

This pull request closes #5. The following changes were made:

- Addition of poetry as a packaging and dependency management tool
- Reorganization of files

2020-10-22 18:22 UTC, omadson requested changes
Make the required changes and send a push.

2020-10-22 18:22 UTC, omadson commented on pyproject.toml
> +[tool.poetry.dependencies]
I think the only dependence on fuzzy c-means is numpy. You do not need to add other libraries.

Put them as development dependencies.

2020-10-22 18:22 UTC, omadson commented on pyproject.toml
> +version = "0.1.0"
fuzzy-c-means is on 1.0.0 release on pypi. can you change this?

2020-10-24 15:26 UTC, omadson commented
just one more thing:
  - add your name to the `README.md` contributors section.

2020-10-24 18:12 UTC, zealberth commented
@omadson could you verify if is everything ok now? thanks

2020-10-24 18:26 UTC, omadson approved these changes
![](https://media.makeameme.org/created/looks-good-to-sxlux9.jpg)

2020-10-24 18:28 UTC, merged